-- Migration to add specialized content fields for varied AI modes
ALTER TABLE contents ADD COLUMN IF NOT EXISTS hook TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS script TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS visual TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS audio TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS viral_reason TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS seo_intro TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS story TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS ending TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS problem TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS solution TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS cta TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS steps_json TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS benefits_json TEXT;
ALTER TABLE contents ADD COLUMN IF NOT EXISTS headings_json TEXT;
